######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 7 13:14:07 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += v4l2_cam.h V4l2Cam.h
SOURCES += main.cpp v4l2_cam.cpp V4l2Cam.cpp
